### ISSUE TITLE
Kibana Visualization does not have Bulgaria

### ISSUE THREAD

**Issue by sbaychev** [elastic/ems-file-service#105]
**Kibana version**: 6.6.2 and above 

**Elasticsearch version**: 6.6.2

**Server OS version**: macOS Mojave

**Browser version**: chrome, any

**Browser OS version**: -

**Original install method (e.g. download page, yum, from source, etc.)**: docker image from docker.elastic.co/kibana/kibana-oss:6.6.2

**Steps to reproduce**:
 1. Create a new index in ElasticSearch
 2. Use/ Map the index in Kibana
 3. Go to "Visualize", "Create a Visualization" and use "Region Maps"

**Describe the feature**:  Am trying to use the Vector Maps for "New Visualization", there are a number of European countries, but Bulgaria is missing. Would be great if you can add it as provinces and regions. I can provide the geojson files.

**Comment by jsanz** [comment]
Hi @sbaychev, Bulgaria administrative boundaries were added by @nickpeihl to the `feature-layers` branch at https://github.com/elastic/ems-file-service/commit/f47676b9aeafd5cffffd8feae2ebdfcb676fa848#diff-ec19aacbf76f5cb2e9225019f5f53b4b, we are planning to release to production that branch soon, thanks for your patience.
