### ISSUE TITLE
Remove html attribution from raster style json

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/ems-file-service#118]
Raster styles have a formatted markdown string for attribution. This can be removed, since the localized attribution is already listed at the top-level.

e.g.:
- https://tiles.maps.elastic.co/v7.2/manifest : has localized attribution
- https://tiles.maps.elastic.co/styles/osm-bright.json : no need for attribution

**Comment by nickpeihl** [comment]
@thomasneirynck Is it preferable to remove the attribution entirely from the layer styles? Alternatively, we could rewrite the style definitions to include a safe HTML link (ex. `<a href="https://www.openstreetmap.org/copyright" rel="noopener">OpenStreetMap contributors </a> ...`) based on the `en` localized values in the root manifest.

This could ensure that any non-Kibana usage of tile services by users (regardless of EMS TOS) maintain attribution when using mapping libraries that conform to the tilejson spec.

**Comment by nickpeihl** [comment]
After speaking offline with @thomasneirynck , we agreed that it makes sense to dynamically rewrite the `attribution` property in style manifests based on the root manifest properties. The style manifests will contain safe HTML links like the example above.
