### ISSUE TITLE
Add alpha 2 code for Switzerland Cantons

### ISSUE THREAD

**Issue by dschneiter** [elastic/ems-file-service#122]
Selecting a data field containing the official 2-alpha canton codes does not seem to match the `ISO 3166-2 code` join field for the `Switzerland Cantons` vector map 

<img width="1171" alt="Screen Shot 2019-08-17 at 21 25 53" src="https://user-images.githubusercontent.com/1571991/63216453-e28f9980-c135-11e9-92d9-47a7c003455b.png">

**Comment by nickpeihl** [comment]
The region codes in your data are missing the two letter country code (e.g. CH-VD, CH-ZH). The full ISO code for regions is required to maintain distinctiveness when multiple region maps are displayed on a dashboard. For example, [Germany](https://maps.elastic.co/#file/germany_states) and [Switzerland](https://maps.elastic.co/#file/switzerland_cantons) both have subdivisions with the two letter code "BE". 

[This blog post](https://www.elastic.co/blog/new-country-subdivision-vectors-in-the-elastic-maps-service) shows an example of data similar to yours and how a scripted field can be used to construct the correct ISO code from documents in Elasticsearch provided that the documents also have a country code field.

**Comment by dschneiter** [comment]
@nickoeihl: then please let‘s add an option for the alpha2 code which is the common way to denote cantons in Switzerland. This used to work in 6.x releases

**Comment by dschneiter** [comment]
@nickpeihl: can we consider an option for an alpha2 only code which is the common way to denote cantons in Switzerland? This used to work in 6.x releases... (typically combined with a filter query on the country to „avoid“ ambiguity) (similarly for the united states map, where it is is also possible to just use the alpha2 state abbreviations like CA,NY etc)?

**Comment by nickpeihl** [comment]
@dschneiter This sounds reasonable to me. For example, the US States layer has an extra field for the two letter postal abbreviations (e.g. CA for California, NY for New York). Some other countries include statistical codes (ex. `cut-code` for Chile, `logianm` in Ireland).

Do you have a suggestion for the name of the field? Postal code?

**Comment by dschneiter** [comment]
Nope, postal code/zip-code is a different concept. It's about canton codes (which are language independent). So whether it is about "Zürich" (German) or "Zurigo" (Italian) it's always "ZH". It's the identifier which we also use on car plates and in all statistical data available from the Swiss government. I will do some investigation whether we do have a standardized name to reference that field (Canton Code is my suggestion)
