### ISSUE TITLE
Add Vector Layer for Country of Liechtenstein

### ISSUE THREAD

**Issue by BFLB** [elastic/ems-file-service#129]
I am working on a project where I need to get geo-information in and around switzerland, namely get iso_3166_2 codes of certain areas. I have imported vector layer shapes from https://maps.elastic.co/#file/world_countries for Switzerland, Germany, Austria, Italy and France and it works very well.
Unfortunately there is no map available yet for Liechtenstein (https://en.wikipedia.org/wiki/Liechtenstein). This leads to a blind spot between Switzerland and Austria. Please add a Liechtenstein Layer as soon as possible to close that gap.
Thank you very much in advance.

Elasticsearch version : 7.4.0

Sincerly
Bernhard

**Comment by jsanz** [comment]
@BFLB Liechtenstein municipalities were pushed to the `feature-layers` branch at #134, we plan to release it to production soon, thanks for your patience :slightly_smiling_face:
