### ISSUE TITLE
Split Spain boundaries into provinces and regions

### ISSUE THREAD

**Issue by jsanz** [elastic/ems-file-service#142]
At this moment Spanish boundaries store together both provinces and autonomous communities, being the second a higher admin level. We should take out the autonomous communities from the current province's source. 

Since all boundaries have an ISO code we could not do this, since joining with other data will yield the correct data, but for consistency and clarity, like in other countries like the USA or Italy, it's better to have them in different sources.

**Comment by jsanz** [comment]
@nickpeihl we have a fun one here. It happens that some autonomous communities of Spain have a single province, that means that the same boundary contains **two** ISO codes. In Wikidata you can see how for example Cantabria [Q3946](https://www.wikidata.org/wiki/Q3946), it is both an instance of a Province and an Autonomous Community and contains two ISO codes, which is a break on the validation of this property (this is not an isolated case, there's a long list of _violations_ of the rule [here](https://www.wikidata.org/wiki/Wikidata:Database_reports/Constraint_violations/P300#Single_value).

Interestingly, OSM has these two boundaries separated.

* `ES-CB` for the autonomous community, [relation 349013](https://www.openstreetmap.org/relation/349013)
* `ES-S` for the province, [relation 6426101](https://www.openstreetmap.org/relation/6426101)

I will try to adapt the query to retrieve the data from OSM, and just the labels from Wikidata, but if you think there's a better approach let me know.

In fact, we have a few wrong ISO codes in our production Spanish province boundaries. For example, for the province `La Rioja` we have `ES-RI` instead of `ES-LO` :sweat: 

![image](https://user-images.githubusercontent.com/188264/69259786-178d0b80-0bbf-11ea-9fe1-78f0a8426cea.png)

**Comment by nickpeihl** [comment]
Yes, this is an interesting case. I wonder if the Autonomous Community of Cantabria is a separate entity than the Province of Cantabria? If so, the Wikidata entry probably should be split into two entries. At the same time, I would like to avoid unnecessarily fragmenting Wikidata just to suit our use case. 

So, let's adapt the query to retrieve the labels from Wikidata and get the geography and the ISO codes from OSM. Let me know if you need help. 

I have two questions:
* Is this split a breaking change that needs to wait until a major EMS release (v8)? 

* Should correcting the incorrect ISO codes be a hotfix that gets pushed to all versions?

**Comment by jsanz** [comment]
Ok sorry :innocent: not exactly an error in our current data, it's just we hae both provinces AND autonomous communities so for example for Cantabria:

![image](https://user-images.githubusercontent.com/188264/69267241-0ba84600-0bcd-11ea-9cdc-bf3a57a0b52c.png)


To your questions, since we are *removing* data from an existing layer I think we probably should push that layer to v8. The new layer for autonomous communities could be released now, but then we would have two layers with overlapping data which is also weird so I would put both for v8. Also that way we can fix also the names of the boundaries to remove the common denominators as we've been doing lately. Makes sense?

**Comment by nickpeihl** [comment]
lgtm! We will release the new Spain layers in v8. 

Thanks for looking into this.
