### ISSUE TITLE
[7.6] Sync future EMS releases with stack releases

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#144]
Currently, new EMS versions are only released when introducing new features or breaking changes. For example, v6.6 introduced localized languages, v7.0 had breaking changes to France depatments, and v7.2 introduced vector tile basemaps. This meant the EMS release was not explicitly tied to the stack release (Kibana v7.2, v7.3, v7.4 all use the EMS v7.2 release).

To support [relative URLs in the tiles and vector manifests](https://github.com/elastic/ems-file-service/issues/141) it is necessary for clients (ex. [ems-client](https://github.com/elastic/ems-client)) to know which EMS version to connect to. The easiest way to do that is match the client and EMS minor releases. 

I propose we start publishing EMS releases for every minor release of the stack starting with v7.6. Since vector files are published at the root level (ex. `/files/world_countries_v1.geo.json`), the only duplication should be the version manifests (ex. `/7.6/manifest`, `/v7.7/manifest`). So there is very little overhead for the file service. Tile service overhead is still being investigated, but should be similarly little.

cc @thomasneirynck @nyurik @jsanz

**Comment by nyurik** [comment]
we could of course just have a separate "relative" endpoint - this way we don't have to maintain and update versions every time stack is released.  Both have their pros/cons.

**Comment by nickpeihl** [comment]
this is completed as of https://github.com/elastic/ems-file-service/pull/143
