### ISSUE TITLE
Test that feature properties are constrained to only those in source metadata

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#151]
This is the inverse of #53.

For example, the [source metadata of Chile Regions](https://github.com/elastic/ems-file-service/blob/master/sources/cl/chile-regions.hjson) has the following `fieldMapping`:

```
fieldMapping: [
        {
          type: id
          name: iso_3166_2
          desc: ISO-3166-2 identifier
        }
        {
          type: id
          name: cut
          desc: CUT code
        }
        {
          type: property
          name: label_en
          desc: Region name (English)
        }
        {
          type: property
          name: label_es
          desc: Region name (Spanish)
        }
    ]
```

Features in the associated GeoJSON file for Chile Regions may only have these properties and no others (`iso_3166_2`, `cut`, `label_en`, `label_es`). If one or more features in the GeoJSON file has a property not listed in the `fieldMapping` (ex. `label_pt`), the tests should throw an error.

**Comment by jsanz** [comment]
fixed by #152
