### ISSUE TITLE
Add version number to manifest

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/ems-file-service#159]
Manifests are versioned, but we don't publish them with the actual version number. this is now implicit in the URL where it is hosted. Ideally, we publish the version number inside the manifest.

A similar ask for the tile-service.

**Comment by nickpeihl** [comment]
Can you provide a use-case for this? I'm not opposed to it, but I'd like to know how it could be used.

**Comment by thomasneirynck** [comment]
1. the ems-client can validate it retrieves a manifest it supports (this will be more relevant when we'll start users to allow to configure the endpoints)
2. to be in-line with the majority of other metadata specs
 - tilejson: https://github.com/mapbox/tilejson-spec/blob/master/2.2.0/example/osm.layer
 - ArcGIS Rest Services: https://sampleserver6.arcgisonline.com/arcgis/rest/services/
 - WMS: https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WMSServer?request=GetCapabilities&service=WMS
 - elasticsearch :) : http://localhost:9200/

**Comment by nickpeihl** [comment]
I'm going to reopen this and close after all changes are in production.

**Comment by nickpeihl** [comment]
This is done.
