### ISSUE TITLE
Publish EMS v7.9 endpoint

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#174]
We should publish the EMS vector v7.9 endpoint in order to unblock ems-client and ems-landing-page 7.9 releases.

The tiles v7.9 endpoint is already available at https://tiles.maps.elastic.co/v7.9/manifest.

**Comment by jsanz** [comment]
Anything else to include, apart from the same changes as in #168?

**Comment by nickpeihl** [comment]
> Anything else to include, apart from the same changes as in #168?

Nothing else should be needed for creating the endpoint. Sorry, I saw this after I made https://github.com/elastic/ems-file-service/pull/176.
