### ISSUE TITLE
Natural Earth Provinces and States layer

### ISSUE THREAD

**Issue by jsanz** [elastic/ems-file-service#177]
This issue tracks the work to improve [Natural Earth Admin 1](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/) dataset. @nickpeihl has already reported the regions that need some fix on [a google spreadsheet](https://docs.google.com/spreadsheets/d/1a9_Ib7Lha1l5yqHxPssUX1tWVziegQXws8No-006PC4/edit?usp=sharing).

@nickpeihl and I will be fixing geometries and eventually merge all together in a new dataset that would be merged with original NE data to produce the dataset to be served on EMS.

**Comment by thomasneirynck** [comment]
related https://github.com/elastic/ems-file-service/issues/170
