### ISSUE TITLE
Update World Countries Layer

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#179]
The geometry in the [world countries layer](https://maps.elastic.co/#file/world_countries) is very low resolution and often jagged. We could update this layer to a moderately higher resolution that is more consistent with the upcoming administrative regions layer. 

I propose we do an in place update for all versions of EMS. 

The updated geojson layer may be around 5MB which is considerably larger than the current 627KB version. But we can experiment with simplification to get it smaller if necessary. Alternatively, we can limit the updated layer to EMS v2 (Kibana v6.2+) and publish as a 3.4MB TopoJSON file.

**Comment by jsanz** [comment]
This issue was fixed by #196, now Worl Countries dataset is derived from Admin regions and served as a more detailed dataset.
