### ISSUE TITLE
Review Bosnia-Herzegovina regions

### ISSUE THREAD

**Issue by jsanz** [elastic/ems-file-service#183]
Bosnia-Herzegovina region `BAH-BIH` appears repeated several times in the new regions dataset

![image](https://user-images.githubusercontent.com/188264/91995563-40d6ec80-ed38-11ea-87a2-4403644ef5be.png)

We need to check if those are all part of a single bigger region and also review the rest of the country features.

cc. @nickpeihl

**Comment by nickpeihl** [comment]
In my preliminary analysis shows I found [canton codes that were deprecated in 2015](https://en.wikipedia.org/wiki/ISO_3166-2:BA#Canton_codes). It looks like the codes were corrected in the attributes, but the canton boundary lines are still present. This is why we see the duplicates.
