### ISSUE TITLE
Missing province code

### ISSUE THREAD

**Issue by televideocomsrl** [elastic/ems-file-service#189]
The ISO 3166-2 code for the "Province of South Sardinia" province in the Italy Provinces map is missing:

{ properties":{"istat":"111","iso_3166_2":"NULL","label_en":"Province of South Sardinia","label_it":"provincia del Sud Sardegna"}

it should be instead:

{ properties":{"istat":"111","iso_3166_2":"IT-SD","label_en":"Province of South Sardinia","label_it":"provincia del Sud Sardegna"}

**Comment by jsanz** [comment]
Confirmed, sorry for the inconvenience @televideocomsrl, we'll fix that

![image](https://user-images.githubusercontent.com/188264/94563561-29bbe980-0267-11eb-8ebd-446921db2dd3.png)

**Comment by jsanz** [comment]
@televideocomsrl the change from #190 has been deployed and available at the [Italy Provinces dataset](https://maps.elastic.co/#file/italy_provinces).

Please, let us know if you have further comments.
