### ISSUE TITLE
Missing regions and country boundaries

### ISSUE THREAD

**Issue by jsanz** [elastic/ems-file-service#194]
After merging #192 and doing a visual exploration I saw a couple of issues on the geometries that led me to run a full difference of the geometries of Natural Earth countries dataset and our derived one, confirming we need to review:

* Part of North Virginia corresponding to Accomack and Northampton counties
* Zuid-Holland in the Netherlands is not contributing to the countries dataset (wrong country identifier)
* Disputed territory in North Cyprus

| ![image](https://user-images.githubusercontent.com/188264/96581943-e3443280-12da-11eb-9511-10c4abab718d.png)  	| ![image](https://user-images.githubusercontent.com/188264/96581884-cc054500-12da-11eb-910e-88a7d3cedfcf.png)   	|  ![image](https://user-images.githubusercontent.com/188264/96582235-433ad900-12db-11eb-920f-513be75bbed1.png) 	|
|---	|---	|---	|
|North Virginia | Netherlands | Cyprus

To ensure no other areas are missed I did the following steps:

1. difference analysis in QGIS between `ne_admin_0_countries` and our `world_countries.v7.geo.json`
2. promote multi-part geometries into single parts
3. compute area* for all geometries
4. order them by area

\* _area is just for relative ordering since this computed value is no correct for this data coordinate system_ 

![image](https://user-images.githubusercontent.com/188264/96582482-a593d980-12db-11eb-9a4c-8bd595c1bfc5.png)

I'll create a new PR against `feature-layers` for this.

**Comment by nickpeihl** [comment]
This think this was closed by #195. @jsanz, please re-open if I'm wrong.
