### ISSUE TITLE
World Countries not working in Version 2

### ISSUE THREAD

**Issue by cabarc** [elastic/ems-file-service#198]
Today we found an issue in our Region Maps Visualizations, they aren't able to load and promps the following error,

"Error downloading vector data
Cannot download https://vector.maps.elastic.co/blob/5659313586569216?elastic_tile_service_tos=agree&my_app_version=YYY&license=XXX file. Please ensure the CORS configuration of the server permits requests from the Kibana application on this host."

After some checks, I thought it could be a API problem in maps.elastic.co
    For one hand, maps.elastic.co v1 works properly for "World Countries" layer:
        https://maps.elastic.co/index.html#file/world_countries
    But it seems to be unavailable for v2 version:
        https://maps.elastic.co/v2/index.html#file/World%20Countries
 
   
If we configure the Region Maps Visualization to another layer, Belgium Regions, in v2 seems to work properly:
    https://maps.elastic.co/v2/index.html#file/Belgium%20Regions

**Comment by jsanz** [comment]
hi @cabarc sorry for the inconvenience I can confirm that manifest for `v2` is pointing to the TopoJSON version of the dataset instead of GeoJSON and that is confusing the EMS Client both in Kibana and maps.elastic.co. We are going to work on this today.

**Comment by jsanz** [comment]
@cabarc we deployed the fix yesterday evening, and the v2 manifest now reports the correct link to the GeoJSON dataset. Please reopen if you see anything wrong. Again, sorry for the interruption in the service.
