### ISSUE TITLE
EMS v7.11

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#200]
- [x] File Service #201 
- [x] Tile Service
- [x] ems-client elastic/ems-client#54
- [x] ems-landing-page elastic/ems-landing-page#283
- [x] bump ems-client in kibana and update ems-landing-page link in kibana https://github.com/elastic/kibana/pull/84136

@jsanz Do you feel comfortable creating PRs for the above? See https://github.com/elastic/ems-file-service/issues/181 for reference.

**Comment by jsanz** [comment]
Yep I'll work on this today and ping you for questions 👍

**Comment by jsanz** [comment]
@nickpeihl PR for Kibana has been merged. Keeping this open if you agree since we still have to change the default branch for https://maps.elastic.co to show 7.11 branch.
