### ISSUE TITLE
Add regex pattern for fields in manifest

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#209]
We might want to consider adding a regex pattern property to the vector file fields. This could be useful for clients that want to automatically suggest a field matching a pattern without downloading the full file. See https://github.com/elastic/kibana/pull/94969. 

cc @jsanz @thomasneirynck 

An example is below.

```json
{
  "version": "7.13",
  "layers": [
    {
      "layer_id": "world_countries",
      "created_at": "2020-10-28T16:16:08.720286",
      "attribution": [ ... ],
      "formats": [ ... ],
      "fields": [
        {
          "type": "id",
          "id": "iso2",
          "regexp": /^[A-Z]{2}$/,
          "label": { ... }
        },
        {
          "type": "id",
          "id": "iso3",
          "regexp": /^[A-Z]{3}$/,
          "label": { ... }
        },
        {
          "type": "property",
          "id": "name",
          "regexp": /^.*$/,
          "label": { ... }
        }, ... ]
...
```

**Comment by thomasneirynck** [comment]
another field to consider would be to add a regex-pattern for a fieldname alias. 

For example, 
- so we can match `iso`-fields to their ECS equivalents
- for more generic naming. e.g. a field like `iso2_code`, `iso2-code`, `iso-code` in it will likely be compatible with `world_countries#iso2)

**Comment by nickpeihl** [comment]
> another field to consider would be to add a regex-pattern for a fieldname alias.

I added #210 for this.
