### ISSUE TITLE
Add administrative region layers for countries in the Arabian Peninsula

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#224]
The countries we want to add are:

- Bahrain
- Kuwait
- Oman
- Qatar
- Saudi Arabia
- United Arab Emirates
- Yemen

The boundaries and Romanized names can be pulled from the administrative regions layer. We also want to add Arabic names, but we'll need to see if those are available from Wikidata or other sources.

**Comment by kelastic** [comment]
Many thanks for your support with this. It is much appreciated!

**Comment by nickpeihl** [comment]
These layers are now available in production.
