### ISSUE TITLE
New Zealand EMS administrative map seems to be missing. Can this please be added?

### ISSUE THREAD

**Issue by aniketedakhe** [elastic/ems-file-service#249]

**Comment by jsanz** [comment]
@aniketedakhe the EMS [global administrative regions](https://maps.elastic.co/#file/administrative_regions_lvl2) layer contains boundaries for New Zealand, so you could join by the regions ISO code `NZ-...`.

![image](https://user-images.githubusercontent.com/188264/167092505-1c8e05d6-4a13-4bce-84e2-7fc2d3e4210a.png)


What identifiers or data is missing for your use case?
