### ISSUE TITLE
Test for existence of join fields in vector data

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#53]
We should have unit tests that verify that all join fields in the manifest files actually exist in the vector data. This would allow us to catch data errors like in #51 prior to publishing.

**Comment by jsanz** [comment]
After discussion at #152 @nickpeihl and I agreed that it's OK to have fields not present in the data. This is the case for labels in a few countries where some regions don't use a language used in other parts of the country (reminder that those labels are marked as `OPTIONAL` in the SPARQL query).

Still, an optional test has been added and documented on the repo `README.md` to check this condition.
