### ISSUE TITLE
Geometry compatibility issues

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/ems-file-service#7]
Some of the geoJson data is not compatible with other technologies.

This is likely due to some of the features being malformed; e,g. faulty inner ring orientations, or self-crossing polygons, are possible causes.

There's two known cases where data from EMS is not compatible.

1. The world layer is not compatible with Elasticsearch when `ignore_malformed` is turned off. This settings is under consideration to be deprecated. I didn't double check, but I think a couple of countries were throwing errors (e.g. Canada, Russia).
2. The French department layer is not compatible with the Mapbox GL JS API (tested on v0.45.0)

There is probably more. 

Is there a way we can correct/fix the data, perhaps as part of the automated data pipeline?

**Comment by thomasneirynck** [comment]
(2) likely no longer relevant, is working fine on maps.elastic.co.

**Comment by nickpeihl** [comment]
Fixed in #54.
