### ISSUE TITLE
Style/generate new basemaps for muted and dark themes of world layer

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/ems-file-service#8]
We only have a single style for the road-data.

Kibana uses CSS transforms on these images to:
- mute the style to create unsaturated/desatured styles
- invert the colors for a dark theme

This way, we generate 3 different basemaps, from that single raster layer.

----------

1) road_map; no desaturatization

![image](https://user-images.githubusercontent.com/1833023/39776764-bdc50426-52cf-11e8-8c13-04313c08f29d.png)

2) road_map; desaturation

![image](https://user-images.githubusercontent.com/1833023/39776804-d8548a64-52cf-11e8-8f8e-6c1e5def1c5e.png)

3) road_map; dark theme

![image](https://user-images.githubusercontent.com/1833023/39776867-07ee5f5c-52d0-11e8-9bf9-94641c410df2.png)

------------

We should deprecate this approach as soon as we can. https://github.com/elastic/kibana/issues/18657.

-------

With the upcoming EMS v3 we will have the ability to publish multiple baselayers, including multiple styles https://github.com/elastic/infra/issues/2907.

Ideally, we have multiple style-sheets (saturated/unsaturated * day/night). These could then be used for eventual client-side vector rendering too. But we also want this generated as actual images, because we will need continued support for raster based rendering as there are currently no plans to rewrite the Visualizations.

cc @alexfrancoeur @nickpeihl @mentat @nyurik

**Comment by nickpeihl** [comment]
Fixed by #98.
