### ISSUE TITLE
Italy Regions

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#91]
We should have a layer of the regions of Italy along with the existing provinces layer. According to several sources [[1](https://github.com/elastic/kibana/issues/33230#issue-420918516)] [[2](https://en.wikipedia.org/wiki/Provinces_of_Italy#Controversies)], regions are more commonly used than provinces in Italy. One region (Friuli-Venezia Giulia) has even [disbanded its provinces](http://www.consiglio.regione.fvg.it/cms/hp/informazioni/0072.html).

**Comment by jsanz** [comment]
This was fixed at #132
