### ISSUE TITLE
[Maps] EMS seems to limit to 10 zoom levels with Basic license in 8.0.0

### ISSUE THREAD

**Issue by alexfrancoeur** [elastic/ems-file-service#97]
It seems we are limiting 8.0.0 users to 10 zoom levels in master

https://tiles.maps.elastic.co/v2/default/13/2414/3082.png?elastic_tile_service_tos=agree&my_app_name=kibana&my_app_version=8.0.0&license=894371dc-9t49-4997-93cb-8o2e3r7fa6a8

> you are only allowed up to zoom level 10

cc: @nyurik @nickpeihl @thomasneirynck

**Comment by nyurik** [comment]
@alexfrancoeur this is not a correct license.
